services:
  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    container_name: mariadb
    image: mariadb
    restart: on-failure
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception
    env_file: .env
    secrets: 
      - db_password
      - db_root_password

networks:
  inception:
    driver: bridge

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: "/home/szaoual/data/mariadb"
      o: bind
